<?php
/**
 * Plugin Name: Two-Factor Authentication (TOTP) for WooCommerce
 * Plugin URI: https://github.com/MMTWeb/two-factor-auth-totp-for-woocommerce
 * Description: Enhance the security of your WooCommerce store and WordPress admin area with Time-based One-Time Password (TOTP) two-factor authentication. This plugin provides an extra layer of protection against unauthorized access by requiring users to verify their login attempts with a code generated by a TOTP authenticator app (like Google Authenticator).
 * Version: 1.0
 * Author: MMTDEV
 * Author URI: https://mtdev.ovh/
 * Text Domain: two-factor-authentication-totp-for-woocommerce
 * License: GPLv2 or later
 * License URI: https://www.gnu.org/licenses/gpl-2.0.html
 */

/*
This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.
*/

/**
 * WP functions and classes
 */
require_once __DIR__ . '/vendor/autoload.php';

add_action('plugins_loaded','initPluginClasses');

function initPluginClasses(){
    \WooTotpAuth\Src\WooTotpAutoloaderClass::init(); 
}

/** Include Wordpress functions */
require_once __DIR__ . '/includes/WooTotpHideTitle.php';
require_once __DIR__ . '/includes/WooTotpLoginPageCreate.php';
require_once __DIR__ . '/includes/WooTotpLoginPageShortcode.php';
require_once __DIR__ . '/includes/WooTotpCheckRecKeysExp.php';

/**
 * Check if WooCommerce is active on activation
 */
register_activation_hook( __FILE__, 'checkBeforeActivate' );

function checkBeforeActivate()
{
    if(!is_plugin_active( 'woocommerce/woocommerce.php' )){

        deactivate_plugins( plugin_basename( __FILE__ ) );

        wp_die(
            'This plugin requires WooCommerce to be installed and active. 
            <br><a href="' . esc_url( admin_url( 'plugins.php' ) ) . '">Go back</a>'
        );
    }

    set_transient( 'woo_totp_flush_rewrites', true, 60 );
}
?>